# =============================================
# Configuración de Base de Datos MySQL
# =============================================
db.host=localhost
db.port=3306
db.name=750251004_6_eventosParaCongreso
db.username=7502510004_dcolmenarez
db.password=2407Alejo!

# =============================================
# Configuración SMTP (JavaMail)
# =============================================
smtp.host=smtp.gmail.com
smtp.port=587
smtp.username=dcolmenarezr@unicartagena.edu.co
smtp.password=lgys hcxq gawf qvpl
smtp.from.address=tu_correo@gmail.com
smtp.from.name=Gestión de Usuarios

